---
- name: Upload Config | upstart | mvml-host
  template:
    src: etc/init/mvml-host.conf
    dest: /etc/init/mvml-host.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart mvml-host

- name: Replace String | mvml-host | content server
  replace:
    dest: /opt/mvml/host/views/getting-started.html
    regexp: "content.dev.mvml.net"
    replace: "content.mvml.net"
  notify:
    - Restart mvml-host
