---
- name: Upload Config | monit | mvml-host
  template:
    src: etc/monit/conf.d/mvml-host
    dest: /etc/monit/conf.d/mvml-host
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart mvml-host
    - Restart monit

- name: Replace String | mvml-host | content server
  replace:
    dest: /opt/mvml/host/views/getting-started.html
    regexp: "dev.mvml.net"
    replace: "mvml.net"
  notify:
    - Restart mvml-host
