---
- name: Directory Exists | /opt/mvml/
  file:
    state: directory
    path: /opt/mvml/
    owner: root
    group: root
    mode: 0644

- name: Pull Repo | mvml-host
  git:
    repo: https://github.com/JScott/mvml-host.git
    dest: /opt/mvml/host
    version: master
    accept_hostkey: yes

- name: Install Packages | from packages.json
  command: "chdir=/opt/mvml/host /usr/bin/npm install"
