---
- name: Directory Exists | /opt/mvml/
  file:
    state: directory
    path: /opt/mvml/
    owner: root
    group: root
    mode: 0644

- name: Pull Repo | mvml-host
  git:
    repo: git@github.com:JScott/mvml-host.git
    dest: /opt/mvml/host
    version: master

- name: Install Packages | npm package dependencies
  npm:
    path: /opt/mvml/host/
