---
- name: Directory Exists | /opt/mvml/
  file:
    state: directory
    path: /opt/mvml/
    owner: root
    group: root
    mode: 0644
  notify:
    - Start mvml-host

- name: Pull Repo | mvml-host
  git:
    repo: https://github.com/JScott/mvml-host.git
    dest: /opt/mvml/host
    version: master
    accept_hostkey: yes

- name: Install Packages | from packages.json
  npm: path=/opt/mvml/host state=latest
