---
- name: Upload Config | upstart | mvml
  template:
    src: etc/init/mvml.conf
    dest: /etc/init/mvml.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart mvml

- name: Modify Config | mvml | content server
  lineinfile:
    dest: /opt/mvml/parse/config.yaml
    regexp: "^content_server:"
    line: "content_server: content.mvml.net:6865"
  notify:
    - Restart mvml

- name: Replace String | mvml | api server
  replace:
    dest: /opt/mvml/parse/public/js/mvml-api.js
    regexp: "direct.dev.mvml.net"
    replace: "direct.mvml.net"
  notify:
    - Restart mvml
